Smarti Version 0.1.0
mrsimpson/Rocket.Chat pull request #34
Opened 2017-07-04 11:09 UTC by tkurz

[NEW]

Hi @mrsimpson 

Hi, here comes the first version of the Smarti Plugin. Basically it includes a new Knowledge Base Adapter for the Smarti Backend. Furthermore it includes a lightweight client part which loads a script provided by Smarti into the Rocket.Chat frontend. The actual Frontend Script uses the Realtime API (slightly extended by this Plugin). The Plugin can be configured via the Rockte.Chat admin UI. I am not sure if I included the "close room" operation correctly, so please took a closer look into that. In add

2017-07-04 17:47 UTC, mrsimpson requested changes
Hi @tkurz ,
please find some comments included. Most are minor. Submitting a context to Smarti should be possible though. Also I wonder about the redundant setting.
Kindly revise.
Cheers, Oliver

2017-07-04 17:47 UTC, mrsimpson commented on packages/assistify/config.js
> +	RocketChat.settings.add('DBS_AI_Redlink_Hook_Token', '', {
@tkurz what is the *configured* token used for?

2017-07-04 17:47 UTC, mrsimpson commented on packages/assistify/package.js
> +	//TODO add jquery?
jQuery is part of Blaze (the templating engine) (@see .meteor/local/build/programs/web.browser/packages/blaze.js)
still, requiring it explicitly should do no harm `api.use('jquery', 'client');`

2017-07-04 17:47 UTC, mrsimpson commented on packages/assistify-help-request/client/views/tabbar/HelpRequestActions.js
> +						RocketChat.models.HelpRequests.findOneByRoomId(instance.data.roomId)//TODO is this correct?
@tkurz it should be

2017-07-04 17:47 UTC, mrsimpson commented on packages/dbs-ai/client/views/app/tabbar/smarti.js
> +				inputCssSelector:'.autogrow-shadow'
@tkurz This is about the input box (in order to copy to), right? if so, what about `$('#chat-window-${ instance.data.roomId } .input-message')`

2017-07-04 17:47 UTC, mrsimpson commented on packages/dbs-ai/server/config.js
> +	RocketChat.settings.add('DBS_AI_Redlink_Hook_Token', 'key123', {
@tkurz difference to the setting in https://github.com/mrsimpson/Rocket.Chat/pull/34/files#diff-8e83d6a3163a81272f59768476959fa7 ?

2017-07-04 17:47 UTC, mrsimpson commented on packages/dbs-ai/server/lib/Smarti.js
> +		//TODO add options here?
@tkurz which options do you mean? Header options?
What about transmitting a context?

2017-07-04 17:47 UTC, mrsimpson commented on packages/dbs-ai/server/lib/Smarti.js
> +		if(this.urlParams.token && this.urlParams.token == RocketChat.settings.get('DBS_AI_Redlink_Hook_Token')) {
ah, is the hook token a "secret"? Then, we should at least md5-it, not?

2017-07-04 17:52 UTC, mrsimpson commented
@tkurz and can you please PR to mrsimpson:develop?

2017-07-17 11:11 UTC, tkurz commented on packages/assistify/config.js
> +	RocketChat.settings.add('DBS_AI_Redlink_Hook_Token', '', {
it is used to verify if a analysis result is send by a trusted source

2017-07-17 11:15 UTC, tkurz commented on packages/assistify/package.js
> +	//TODO add jquery?
the question was about jquery which is used by the bundled smarti script. It is included/packaged there which is maybe also not a good solution. requirejs would be the best solution?

2017-07-17 11:45 UTC, mrsimpson commented on packages/assistify/package.js
> +	//TODO add jquery?
@tkurz: already undestood. In my reply, you can find the declaration of dependency which will make sure jquery is available.

2017-07-17 11:46 UTC, mrsimpson commented on packages/assistify/package.js
> +	//TODO add jquery?
@tkurz: already undestood. In my reply, you can find the declaration of dependency which will make sure jquery is available.

2017-07-19 19:43 UTC, mrsimpson commented
merged to develop, test it in an integrated manner

2017-07-19 19:43 UTC, closed without merging